### ISSUE TITLE
Requested url / was not found

### ISSUE THREAD

**Issue by RonanCastro** [cattr-app/backend-application#2]
Trying run in localhost.
> php artisan server 
Return this on browser
{
"success": false,
"message": "Requested url / was not found",
"error_type": "http.request.not_found"
}

**Comment by vermorag** [comment]
It is normal that when you try to access running backend application it shows you a 404 error. It only API. So if you want to use it you must also set up frontend part from https://github.com/cattr-app/frontend-application or if you just want to test API you can request `/status` endpoint (http:// _your_cattr_backend-part_hostname_ /status) to check that all is functioning.
