### ISSUE TITLE
Demo is offline

### ISSUE THREAD

**Issue by fulldecent** [cattr-app/backend-application#26]
<img width="1303" alt="Screen Shot 2021-10-26 at 12 09 04" src="https://user-images.githubusercontent.com/382183/138918542-3f3553c3-df64-4d38-8fbd-7542a51b47f7.png">

**Comment by vermorag** [comment]
![изображение](https://user-images.githubusercontent.com/25276845/169508980-45cf8046-0c18-4b49-90f1-94fb8b564bd1.png)
Restored online status.
