### ISSUE TITLE
Installation problems and documentation corrections

### ISSUE THREAD

**Issue by DigitalLeaves** [cattr-app/backend-application#3]
Доброе утро! First of all, thank you guys for this tool. Поздравляем!! 

I am going through the installation process now but wanted to share my experience installing the tool and some problems I've found and places where the documentation is not current or shows incorrect information.

My stack:
- Debian 10
- Node 13.3
- MySQL 8.13
- PHP 7.4

Hopefully that will allow you to fix the documentation and improve the installation.
[This is the installation instructions guide](https://docs.cattr.app/?_ga=2.254983360.955999870.1590260367-370235967.1590260367#/en/advanced/) I am using.

# Backend installation.

The instructions say: 
`composer install && php artisan at:install`

That, indeed, shows an error:
```
 There are no commands defined in the "at" namespace.  
                                                        
  Did you mean one of these?                            
      cattr                                             
      cattr:demo                                        
      cattr:intervals                                   
      cattr:make                                        
      cattr:set                                         
      cattr:version                                     
      migrate                                           
      notifications    
```

Changing that to 
`composer install && php artisan cattr:install`
makes the trick.

I created a user for the MySQL database (suggestion: offer the user to do that in the docs, it is not a good idea to use the root MySQL account for 3rd party software.

Then the following error is thrown:

```
In PDOConnection.php line 43:                                                                                                                                                                                     
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)  
```

Fortunately you just need to setup log_bin_trust_function_creators to true (or 1) in MySQL to go past this error: 
```
mysql -u USERNAME -p
set global log_bin_trust_function_creators=1;
```

Then another problem I've found is that after the database was left in this status of "semi-complete", further attempts to install it failed with error:
`SQLSTATE[HY000] [1045] Access denied for user 'cattr'@'localhost' (using password: YES)`

This error is misleading. Instead, the problem is that you need to drop the database, recreate it again, assign privileges again, flush privileges,  and then try again.

After that, and massaging the vi app/Console/Commands/AppInstallCommand.php file, the installation proceeded without further problems.

# Frontend installation

The documentation says:
`Open app/etc directory and copy the env.sample.js file to env.js.`

However, there is no env.sample.js file. There are several ones:
```
-rw-r--r-- 1 root root  870 May 24 07:32 demo.credentials.js
-rw-r--r-- 1 root root  676 May 24 07:32 env.demo.js
-rw-r--r-- 1 root root  677 May 24 07:32 env.production.js
-rw-r--r-- 1 root root  676 May 24 07:32 env.staging.js
```

So you may want to indicate that it is env.production.js (hopefully?).

On step 3, when I run: 
`NODE_ENV=production npm run build`

I get this error
```
ERROR  Failed to compile with 1 errors                                                                                                                                                               
error  in ./app/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /var/www/html/cattr_frontend/app/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
```

Removing node_modules and package-lock.json and running npm update solves this issue, probable some dependencies problem in Node v13.x

I will keep updating this as I go.

**Comment by vermorag** [comment]
Hello.
> The instructions say:
composer install && php artisan at:install

It's a mistake in our docs. I've fixed it now, so you should use `php artisan cattr:install` now.

And, yes, it should be `env.production.js` file for the frontend part. Fixed in the docs.

It's not necessary to create databases on your own, because the installer will do it for you and properly set up the backend part for working with credentials.
When credentials, you entered to the backend part, is wrong, Cattr will not be able to run database migrations to create a database structure that he needs.

**Comment by DigitalLeaves** [comment]
Hi @aVyarvelsky, thanks for your prompt response. I will try to install everything and come up with any mistakes or errors I've found to help you as much as I can in case you want to update the docs or warn people about possible mistakes & solutions.

**Comment by vermorag** [comment]
When you update an initial message of the issue it makes it hard to react on them. =)

You should try to use 12 <= Node.js < 13. We develop frontend application on LTS version of the engine. So v13 can fall with errors.

**Comment by DigitalLeaves** [comment]
Sorry, just wanted to put a full log of my experience installing the app. I thought it was better to have one message instead of separate threads. 

Thanks for the recommendation. I will try to downgrade later :(, because now I tried to login and I got an "Internal server error". So will investigate further.

**Comment by vermorag** [comment]
When you removed the `package-lock.json` node.js has upgraded all packages to the latest versions, but there can appear incompatibilities between app code and library code, so we can't garantee properly working of all parts of application. It has solved issues because of the Node.js version upgrade: we use LST version while you use 13.

**Comment by DigitalLeaves** [comment]
Спасибо @aVyarvelsky. Now it is working fine!
So far so good, starting to explore its possibilities. In my case, I am less interested in the screenshots and more interested in knowing the apps or website URLs the employees of our company are. Is that supported on Cattr? Or perhaps it can be achieved through a module?

**Comment by vermorag** [comment]
We didn't implement such functionality in Cattr yet. But you can achieve it by creating modules for backend, frontend, and desktop part on your own.

**Comment by vermorag** [comment]
Hello @DigitalLeaves . Have you find any other errors or we can close that issue?

**Comment by DigitalLeaves** [comment]
No, I think that was all. Overall, apart from some issues, an excellent installation process. Congratulations. I hope this report was useful.
