### ISSUE TITLE
There is no time tracking

### ISSUE THREAD

**Issue by fulldecent** [cattr-app/backend-application#33]
I opened the URL in the README and clicked through every option.

There is nowhere to turn on time tracking, log hours, or turn on screenshot recording.

Am I missing something?

![out](https://user-images.githubusercontent.com/382183/169575384-ac6fd070-a1f1-42e4-b5f4-9ced8641ed02.gif)

**Comment by vermorag** [comment]
Web application currently don't allow you to track time. Only to read statistics.
You need to install [desktop application](https://cattr.app/desktop/) to use timetracking functionality.

**Comment by fulldecent** [comment]
Thank you // moved to bite-sized issues on front-end application
