### ISSUE TITLE
Error when trying to add task : The selected priority id is invalid.

### ISSUE THREAD

**Issue by zendre4** [cattr-app/backend-application#5]
Hello,

I trying to add add a task but I have the message :

**The selected priority id is invalid.**

* Cattr version: 2.6.0 (install with docker)
* Operating System: Ubuntu 20.04

I have the same bug on the demo site

**Comment by zendre4** [comment]
![2020-05-27_10-57](https://user-images.githubusercontent.com/9673982/83000262-68683b80-a00a-11ea-8819-b25f610459bb.png)

**Comment by vermorag** [comment]
Hello. It's a bug in the recent Docker build. We building and uploading a new version now.
You can fix it at your system by executing at the server: `docker exec -it -u www-data cattr sh -c "php /app/backend/artisan db:seed --class InitialSeeder"`

**Comment by zendre4** [comment]
Thanks ! it's working after that
