### ISSUE TITLE
How to access Docker database remotely

### ISSUE THREAD

**Issue by gorfreed** [cattr-app/backend-application#6]
Hello! My team and I love the Cattr design, and we would like to replace Clockify with it. What blocks us from doing so is that we cannot find a way to integrate the tool into our existing setup, as we need a database interface to our time log submissions. I am assuming Cattr uses an Mysql instance running locally in the container, but I simply cannot find the standard Mysql folders in it.

I exposed the 3306 port of the container and there seems to be some kind of activity, but I am unable to actually connect because I am missing the correct credentials. 

Could you please help me out and tell me how this can be done or at least in which direction to look?

Thanks a lot!

**Comment by vermorag** [comment]
Hello. You can find mysql inside the container at path `/usr/local/mysql/bin`. So, for example, mysqladmin is available under `/usr/local/mysql/bin/mysqladmin`.

Correct login & password you can find in the `.env` file of the backend path.
Please, use `root` as a login and `password` as a password. The database is called `cattr`.

**Comment by gorfreed** [comment]
This is probably less of an issue with Cattr but more with my Laravel knowledge. I am unable to connect with mysqladmin within the container using the .env credentials (Access denied). Basically, I just want to establish an external connection to the database running inside the Cattr container so I can access its data with tools like phpmyadmin running on the Docker host (and then integrate that with other systems). Alternatively, I could change the container Cattr config so it is using an external database running on the host. I am unable to do either for some reason. While I found the mounted backup files (cattr-db)  of the database, I dont know how to use them on the host's database Maria DB and I dont even know what port the mysql is running at inside the container. I tried to look for clues in the setup.sh script but there is just one line and none of the familiar options for mysql. 

I have tried to manually install backend and frontend and met a similar blocker. While the backend is running and the frontend compiled and accessible via my Apache webserver, I cannot log in because of an "internal server error", which is not surprising as I don't know how to configure the frontend config for where to look for the backend. After compiling the frontend data, there is no config file in the dist folder that could do that. The guides for both don't mention how to relate one to another in any way, so I am assuming I must be overlooking the obvious here. 

Thank you so much for the Laravel beginner help!

**Comment by vermorag** [comment]
Okay. Let's start sorting out what we have.
Clarify, please, what exact docker cmd you've used to start Cattr?
To use DB (It should use standard 3306 port) from a container in your external application you need to use key '-p 3306:3306' when you start docker container. That will expose the port from inside to the host machine. Another way is to expose the folder with the MySQL socket.
The other way is to expose MySQL from host to container.
But... you should use only MySQL, not Mariadb. Cattr uses one of the MySQL functions, that MariaDB doesn't have under 10.5 version. (release notes of the MariaDB say, that the required function appeared at 10.5.0, but we don't test it with Cattr yet). If you interest that way, I can refer you to the corresponding docs.

To summ up:
user: `root`
password: `password`
db: `cattr`
port: `3306`
socket path: `/tmp/mysql.sock`
See screenshot below. All commands are done inside container.
<img width="746" alt="изображение" src="https://user-images.githubusercontent.com/25276845/95761511-9e1a7200-0cd6-11eb-8445-adf6a3ec6dfc.png">

Next question: building from source. Are you trying to run at the same machine with one domain? Can you show me your Nginx/apache config?

**Comment by gorfreed** [comment]
Thank you so much for your quick response! I tried your suggestions, so far without success unfortunately. Here is all the info:

Docker Setup
- I have exposed the 3306 port of the container like this: 
![image](https://user-images.githubusercontent.com/6634117/95764276-84feca80-0cb0-11eb-902d-2ac241bfda26.png)
- When trying to connect with a Mysql client via my external facing 7306 port on my host server, the connection is not rejected, but is never established. It's a bit weird, as it just seems to "hang" in suspension. Using any other port than 7306 results in immediate rejection, so I am sure the configuration is correct externally. 
- I actually don't know if 3306 is used by the Cattr container at all, I cannot find any reference to it when browsing the files inside the container.
- I tried to check for "ports used" via lsof -i, but the command doesn't work the same as on the host for some reason.
- I have tried to connect to the Mysql database as per your description, but the root/password credentials are rejected
![image](https://user-images.githubusercontent.com/6634117/95771125-cf854480-0cba-11eb-8590-47e3ca85dd73.png)

**Comment by gorfreed** [comment]
- I have installed Cattr with the bash script on a secondary server. On this one I can successfully enter mysql with root/password credentials. However, I am not getting through to it externally. Just as on my main server, when trying to access my forwarded 7303:3306 port, the connection is simply stuck at logging in
![image](https://user-images.githubusercontent.com/6634117/95773603-12491b80-0cbf-11eb-91b6-6e7dda1a5be5.png)

**Comment by gorfreed** [comment]
How would I change the .env or config variables so it connects to an external Mysql server? If that works, it would solve the matter with the internal db of course.

**Comment by gorfreed** [comment]
Manual Setup

- As I said, I believe that there is a configuration step missing here. As per your setup instructions, the frontend and backend folder have been placed in the /opt directory, but at no point did I tell them about each other so to speak. Is this happening via the web server configuration? My apache.conf looks as follows:

[apache.conf.txt](https://github.com/cattr-app/backend-application/files/5366560/apache.conf.txt)

**Comment by gorfreed** [comment]
Unfortunately, my attempts at connecting the backend inside the container with the database of the host are equally unsuccessful. I have exported the sql data and imported it on a host database, cleared and configured the cache, migrated and installed everything with the respective Artisan commands, but when trying to log into the website I am receiving an error message.

![image](https://user-images.githubusercontent.com/6634117/95863325-580bef80-0d64-11eb-8bdb-50046ed19d45.png)

I have no clue how Laravel works so I am basically just trying whatever I can find on Google. I wish there would be some straightforwardness with config files or Docker compose. I am pretty sure there is an easy way to connect the app to an external database. I would appreciate it a lot if you could give my trial and error approach a bit more direction! @aVyarvelsky

**Comment by gorfreed** [comment]
I just noticed that no matter what host is defined in .env or database.php, artisan will always just attempt to connect to "localhost" only. This seems to be hard-coded somewhere. Too bad I didn't realize it earlier, it would have saved me a lot of time.... Do you know where this "localhost" for the db is defined?

**Comment by vermorag** [comment]
Okay. Let's go next.

You can check open ports in container via `netstat`, for example. See the screenshot below.
<img width="947" alt="изображение" src="https://user-images.githubusercontent.com/25276845/95953729-70dbda00-0e24-11eb-867e-9d2fdc5dd8f7.png">

Moreover: you will not be able to log in from an external source until you will log in from the container. Just because it is only one user: root@localhost, so you should connect exactly via the localhost.

About 7303:3306 ports. I don't fully know, but what software you've used for container creation? If you use portainer it should look like that:

<img width="945" alt="изображение" src="https://user-images.githubusercontent.com/25276845/95954477-93222780-0e25-11eb-8482-e8b883163a09.png">

I've published my mysql port from the test instance, you can try cattr.wolfin.net:7303.

The next one: Laravel has a caching system, that caches config. Have you tried `php artisan config:clear`. (It can be cached again via `php artisan config:cache`) That can be a reason for `localhost` only.

"Unknown database cattr3". If you use mysql from container - there is only `cattr`, not `cattr3` database in it. 

If you want to try Cattr functionality you can use https://demo.cattr.app. Also, we can setup your personal Cattr at your enviroment. Just write to the chat at https://amazingcat.net.

About frontend-backend communication.
The config should be placed in the file: ` app/etc/env.js` according to README.
You interested in `API_URL` param. If it will be set to null, then the frontend will try to communicate with backend at `http://<frontend_domain>/api`. Else - the URL, that you will set.
But if you will use another domain for API you will face with CORS problem. 
You can read more here: https://community.cattr.app/public/d/4-internal-server-error

**Comment by vermorag** [comment]
@gorfreed Any further problems or you have been succeeded with your ideas?

**Comment by gorfreed** [comment]
Apologies for the late response. Unfortunately, we had to go with a makeshift form solution as we had to progress at some point. The team really liked Cattr's clean user interface, but it was impossible for us to make any kind of connection to its very secure container database, thus rendering the platform useless in its insularity. In a time when every department/company has its own tools, being able to "mesh" everything together has become the prime performance factor in ensuring best possible user adoption for me. Are there plans for any kind of integration bridge that would allow for that, e.g. email notifications, REST API, webhooks etc?

**Comment by vermorag** [comment]
We are almost finished with developing webhooks.
Also, our API os open and you can find its open documentation here: https://docs.cattr.app/api/
The same endpoints exist at your instance, so you can try to request them and work with them.
